### ISSUE TITLE
Error: Cannot find module 'worker_threads'

### ISSUE THREAD

**Issue by Jmysy** [tolking/element-pro-components#55]
Error: Cannot find module 'worker_threads' 缺少该 package , 启动时

**Comment by tolking** [comment]
描述不够清晰，提供更多的信息能够让我更好的发现问题

如：版本、vite？vue-cli？在安装了该组件才产生的错误？比较详细的错误产生流程、是否可以被重现？一个小型的错误demo 等

**Comment by Jmysy** [comment]
问题出现于 clone 该仓库代码后，npm install 操作后，dev 启动时所抛出的异常

**Comment by tolking** [comment]
使用 yarn 试试吧

**Comment by Jmysy** [comment]
Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\element-pro-components\node_modules\vite\dist\node\chunks\dep-e9a16784.js:22:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

完整的异常信息，使用 cnpm npm yarn 都试过，也切换 node 版本，都会有该问题

**Comment by tolking** [comment]
抱歉我刚刚下载测试了下没有遇到这个问题，

**Comment by Jmysy** [comment]
方便问一下 node 的对应版本吗，我对应一下环境

**Comment by tolking** [comment]
node 15.14.0

**Comment by tolking** [comment]
很有可能是 vite 的问题，建议先卸载后重新安装 vite ，然后删除 node_modules 下的 .vite 文件夹 在重新启动

**Comment by Jmysy** [comment]
已确认问题，node 版本需要高于 12.0.0
